Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.synced_folder ".", "/vagrant_data", disabled: true


  config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = true
     vb.linked_clone = true

     # Customize the amount of memory on the VM:
     vb.memory = "1024"
     vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end

  config.vm.define "database" do |database|
    database.vm.hostname = "database"
    database.vm.provider "virtualbox" do |vb|
        vb.name = "DATABASE_demo"
    end
    database.vm.network "private_network", ip: "192.168.150.11"
    database.vm.provision "ansible" do |ansible|
        ansible.playbook = "tutorials.yaml"
    end
  end

  config.vm.define "backend" do |backend|
    backend.vm.hostname = "backend"
    # VirtualBox options
    backend.vm.provider "virtualbox" do |vb|
        vb.name = "BACKEND_demo"
    end
    backend.vm.network "private_network", ip: "192.168.150.10"
    # Ansible provisioning
    backend.vm.provision "ansible" do |ansible|
        ansible.playbook = "tutorials.yaml"
    end
  end

  config.vm.define "frontend" do |frontend|
    frontend.vm.hostname = "frontend"
    # VirtualBox options
    frontend.vm.provider "virtualbox" do |vb|
        vb.name = "FRONTEND_demo"
    end
    frontend.vm.network "forwarded_port", guest: 80, host: 12080
    frontend.vm.network "private_network", ip: "192.168.150.12"
    # Ansible provisioning
    frontend.vm.provision "ansible" do |ansible|
        ansible.playbook = "tutorials.yaml"
    end
  end
end
